Issue #14 - Migrating from npm to yarn: done
zonzujiro/tmbd-web-client pull request #15
Opened 2018-06-15 13:17 UTC by iammiro

rm package-lock.json, add yarn.lock and update README.md with instruction of installing project localy

2018-06-15 13:21 UTC, zonzujiro requested changes

2018-06-15 13:21 UTC, zonzujiro commented on README.md
> +`yarn run start`
`yarn start` is ok

2018-06-15 13:22 UTC, zonzujiro requested changes

2018-06-15 13:22 UTC, zonzujiro commented on README.md
> +`yarn install`
just `yarn` will work

2018-06-15 14:12 UTC, iammiro commented on README.md
> +`yarn run start`
Done

2018-06-15 14:12 UTC, iammiro commented on README.md
> +`yarn install`
Done

2018-06-18 06:26 UTC, zonzujiro approved these changes
:fire:

2018-06-18 06:27 UTC, merged