Main page #16:
zonzujiro/tmbd-web-client pull request #20
Opened 2018-06-26 16:04 UTC by iammiro

made base structure of main page, with list of popular movies outputted by default and simple search

2018-06-26 16:15 UTC, zonzujiro requested changes

2018-06-26 16:15 UTC, zonzujiro commented on src/components/MainPage.js
> +import '../App.css';
Pls, use absolute paths. They easier to understand and to reuse.

2018-06-26 16:15 UTC, zonzujiro commented on src/components/MainPage.js
> +    fetch(
Pls, create file `api.js` and move such functionality there

2018-06-26 16:15 UTC, zonzujiro commented on src/components/MainPage.js
> +import React, { Component } from 'react';
You forgot `flow` comment?

2018-06-26 16:15 UTC, zonzujiro commented on src/components/MainPage.js
> +        result => {
Such stuff must be handled thru redux modules

2018-06-26 16:15 UTC, zonzujiro commented on src/components/MainPage.js
> +          console.log(this.state.items);
👀

2018-06-26 16:15 UTC, zonzujiro commented on src/components/MainPage.js
> +        <div>
`<></>`

2018-07-03 11:46 UTC, zonzujiro requested changes
Great work, keep going!

Pls, see the description of redux-ducks-modules. This architecture usually is used for applications with a redux.

2018-07-03 11:46 UTC, zonzujiro commented on package.json
> +    "prop-types": "^15.6.2",
You don't need `prop-types` because you have `Flow`. Pls, remove and use types instead

2018-07-03 11:46 UTC, zonzujiro commented on src/App.test.js
> +import {Provider} from 'react-redux';
Looks like `prettier` not worked

2018-07-03 11:46 UTC, zonzujiro commented on src/actions/actionTypes.js
> +export const MOVIE_LOADING = 'MOVIE_LOADING';
According to ducks-modules action types must be in the module

2018-07-03 11:46 UTC, zonzujiro commented on src/actions/actions.js
> +/* @flow */
Move this to the module.

Also, I think that you should reuse class made by @OleksiyRudenko for API calls

2018-07-03 11:46 UTC, zonzujiro commented on src/actions/actions.js
> +    return fetch(`${BASE_URL}${TOP_FILMS}?${API_KEY}&${SORT_BY_POPULARITY}`)
Can you use `async/await` here? The code will become more understandable

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +import * as MoviesActions from '../actions/actions';
The absolute path here.

Also, about importing of a `*` - usually it is bad for three shaking. So use it with wisdom :)

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +  constructor(props) {
If you wish, you can declare `state`  without constructor like this:

`state = {/* */}`

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +      isLoaded: true,
Fetching of movies is async action, so you will set your flag `isLoaded` right after sending of the request.
Also, such flags must come from module thru `mapStateToProps`

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +  handleSearchChange = event => {
Pls, add types

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +  handleSubmit = event => {
Types

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +    const data = this.props.data;
You can combine both of this lines

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +      return <div>Is loading...</div>;
Pls, leave TODO that we need some `Loading` component and create an issue

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +        <Fragment>
So much `Fragment` 😄 You can use `div` already I think.

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +          <Fragment>
Redundant `Fragment`

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +MainPage.propTypes = {
Remove after adding of types

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +function mapStateToProps(state) {
Why you need `state.defaultMovies`?

2018-07-03 11:46 UTC, zonzujiro commented on src/components/MainPage.js
> +function mapDispatchToProps(dispatch) {
I think better will be if you use just use an object here:

```js
const mapDispathToProps = {
  /* list of actions */
}
```

In such way you will see what concrete actions passed to the container

2018-07-03 11:46 UTC, zonzujiro commented on src/reducers/defaultMoviesReducer.js
> +import initialState from './initialState';
Pls, move to module

2018-07-03 11:46 UTC, zonzujiro commented on src/reducers/defaultMoviesReducer.js
> +import { MOVIE_LOADING, MOVIE_LOADED } from '../actions/actionTypes';
Absolute path

2018-07-03 11:46 UTC, zonzujiro commented on src/reducers/defaultMoviesReducer.js
> +export const defaultMovies = (state = initialState.data, action) => {
Types?

2018-07-06 07:32 UTC, zonzujiro requested changes
Ok, final push. You can do it! 💪

2018-07-06 07:32 UTC, zonzujiro commented on src/components/MainPage.js
> +    this.state = {
You have this data in store so you must just pass it from the redux store. No need to save the copy in the local state.

2018-07-06 07:32 UTC, zonzujiro commented on src/components/MainPage.js
> +  defaultAction: Object,
`defaultAction` is a bad naming. Pls, rename to something obvious.

2018-07-06 07:32 UTC, zonzujiro commented on src/components/MainPage.js
> +  handleSearchChange = (event: SyntheticEvent<any>) => {
Pls, don't use `any`.  Or set concrete action or you can do something like this:

```js
handleSearchChange = ({ target }: { target: HTMLInputElement }) =>
```

In such way you will add type only for `target`

2018-07-06 07:32 UTC, zonzujiro commented on src/components/MainPage.js
> +          <Fragment>
Pls, remove this `Fragment`, because it is redundant

2018-07-06 07:32 UTC, zonzujiro commented on src/components/MainPage.js
> +  return { data: state.movies, isLoaded: true };
`isLoaded` also should be taken from the store

2018-07-06 07:32 UTC, zonzujiro commented on src/modules/searchMoviesReducer.js
> +import api from 'utils/Tmdb.js';
I think, that better will be if this module will be for all the movies, not only for some functionality as searching.  In such way, you will have fewer modules in the application.

So naming `movies` will fit better.

2018-07-06 07:32 UTC, zonzujiro commented on src/modules/searchMoviesReducer.js
> +export default function reducer(state: Object = initialState, action: Object) {
Pls, leave `TODO` that we need some concrete types for the state and for actions.

2018-07-06 07:32 UTC, zonzujiro commented on src/modules/searchMoviesReducer.js
> +    const movies = api.searchAmong('multi', searchParams);
`async/await`? 😄

2018-07-06 07:32 UTC, zonzujiro commented on src/components/MainPage.js
> +import * as defaultMoviesReducer from 'modules/defaultMoviesReducer';
Why do you need `defaultMoviesReducer ` again?

2018-07-06 09:23 UTC, OleksiyRudenko commented on .huskyrc
> +    "pre-push": "echo 'husky: Running pre-push tasks...' && yarn prettify && yarn lint"
Special thanks for making this consistent with project's package manager in use

2018-07-07 11:48 UTC, zonzujiro approved these changes
Great job!

2018-07-07 14:10 UTC, OleksiyRudenko approved these changes
Well done! Please, merge into master

2018-07-08 06:01 UTC, merged

2018-07-08 06:02 UTC, iammiro commented
Done. Thanks for review.