Issue #3 - Set up redux: done, create and connect store, middlewares,…
zonzujiro/tmbd-web-client pull request #6
Opened 2018-06-12 17:07 UTC by iammiro

… add support of redux-dev-tools, add root reducer

2018-06-12 17:21 UTC, zonzujiro requested changes
Good job, but see comments

2018-06-12 17:21 UTC, zonzujiro commented on src/App.js
> +export const test = (state = initState, action) => {
Pls, create module in  `modules` for this one

2018-06-12 17:21 UTC, zonzujiro commented on src/store/reducers.js
> +import {combineReducers} from 'redux';
I think better place this one in to `modules` to because all our reducers will be there

2018-06-13 11:14 UTC, zonzujiro commented
Looks like you forgot to use styles of prettier. In other - lgtm

2018-06-13 11:27 UTC, myroslav-kolomiiets commented on src/App.js
> +export const test = (state = initState, action) => {
Done

2018-06-13 11:27 UTC, myroslav-kolomiiets commented on src/store/reducers.js
> +import {combineReducers} from 'redux';
Done

2018-06-13 11:28 UTC, zonzujiro approved these changes
🚢

2018-06-13 11:28 UTC, merged